### PR TITLE
Ssc

### PR DESCRIPTION
**Pull request by rauljmz**
I seem to have upgraded some dependencies, so you might want to take the code changes only.

### CODE REVIEW

**Comment by kevinobee** [comment]
Awesome, thank you :-)

-----Original Message-----

**Comment by rauljmz** [comment]
We might want to add some more info in the Analytics tab. I think it would
be great to add information about personalization/testing
components/content. I will look at it once I get more familiar with 8!

**Comment by kevinobee** [comment]
That would be great to have. I've added support for Asimov, web api and mvc controllers. It now works pretty well as a security surface explorer / auditing tool.

-----Original Message-----

**Comment by rauljmz** [comment]
It may take a while to get familiar with 8 though... every time I turn it
on (and I mean just log on to the desktop!) I can hear my Surface puffing.

**Comment by kevinobee** [comment]
The puffing is the speak cshtml pre compilation. You can comment out the offending config and take a load off that cpu.

-----Original Message-----

**Pull request merged**
